esphome:
  name: intercom-device
  friendly_name: Intercom Device
  platform: ESP32
  board: esp32dev
  framework:
    type: arduino

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  # Enable fallback hotspot
  ap:
    ssid: "Intercom Fallback"
    password: "intercom123"

# Enable logging
logger:
  level: DEBUG

# Enable Web API for debugging
api:
  encryption:
    key: !secret api_encryption_key

# OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# Status LED (optional)
status_led:
  pin:
    number: GPIO2
    inverted: true

# I2S Audio Configuration
i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26
  i2s_dout_pin: GPIO22  # Speaker output
  i2s_din_pin: GPIO33   # Microphone input
  mode: stereo
  bits_per_sample: 16bit
  sample_rate: 16000Hz

# Text Sensor for connection status
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC Address"

# Binary Sensor for call state
binary_sensor:
  - platform: status
    name: "Intercom Status"

# Custom Intercom Component
# This uses the custom component defined in intercom_component.h/cpp
external_components:
  - source: local
    components: [ intercom ]

intercom:
  id: intercom_device
  signaling_server: "ha.shafferco.com"
  signaling_port: 1880
  signaling_path: "/endpoint/webrtc"
  audio_port: 5004

# UDP for Audio Streaming
socket:
  - platform: udp
    id: audio_udp
    local_port: 5004
    on_data:
      - lambda: |-
          // Receive audio data and play via I2S
          // This is a simplified example - actual implementation would need
          // proper RTP packet handling

# Scripts for call management
script:
  - id: start_call
    then:
      - lambda: |-
          // Initiate a call
          ESP_LOGD("intercom", "Starting call");
  
  - id: end_call
    then:
      - lambda: |-
          // End current call
          ESP_LOGD("intercom", "Ending call");
  
  - id: accept_call
    then:
      - lambda: |-
          // Accept incoming call
          ESP_LOGD("intercom", "Accepting call");

# Switches for call control
switch:
  - platform: template
    name: "Start Call"
    lambda: |-
      return false; // Read-only
    turn_on_action:
      - script.execute: start_call
  
  - platform: template
    name: "End Call"
    lambda: |-
      return false; // Read-only
    turn_on_action:
      - script.execute: end_call
  
  - platform: template
    name: "Accept Call"
    lambda: |-
      return false; // Read-only
    turn_on_action:
      - script.execute: accept_call

# Sensors for call metrics
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  
  - platform: uptime
    name: "Uptime"

